### ISSUE TITLE
How to use it with import

### ISSUE THREAD

**Issue by Colir** [igorskyflyer/npm-scrollend-polyfill#1] opened 2024-09-13 13:40 UTC
Hi, i think I'm dummy,
but I can't figure how the polyfill works.

here is my code

`
import scrollend from 'scrollend-polyfill';

export default function(){

    window.addEventListener('click', (e) => {
        if( e.target.classList.contains('preventStickyNavShow') ){
            cancelStickyNavShow = true;
            document.addEventListener("scrollend", (evt) => {
                    console.log("done scrolling");
                    cancelStickyNavShow = false;
                },{ once: true });
             
        }  
    })
}
`
But this has no effect in Safari (this browser doesn't support the native scrollend event)
I've also tried window.addEventListener('scrollend') without success.

I'm missing out on how to init the polyfill.

Can you help me.
Thank you

**Comment by igorskyflyer** [comment] 2024-09-13 22:36
Hello @Colir, thank you for taking an interest in using my scrollend polyfill.  

In order to provide you with some tips and fix(es), could you please provide me with the full source code of the page using it or a repository so I can pinpoint the exact issue.

Thanks. 😁

**Comment by Colir** [comment] 2024-09-16 07:37
Hi @igorskyflyer ,
Sorry, I found the problem:
the import must be done with 
`
import scrollend from '@igor.dvlpr/scrollend-polyfill';
`
and not 
`
import scrollend from 'scrollend-polyfill';
`
Everything's working fine now, thanks.

**Comment by igorskyflyer** [comment] 2024-09-16 11:38
> Hi @igorskyflyer ,
> Sorry, I found the problem:
> the import must be done with 
> `
> import scrollend from '@igor.dvlpr/scrollend-polyfill';
> `
> and not 
> `
> import scrollend from 'scrollend-polyfill';
> `
> Everything's working fine now, thanks.

Got it, yes, there are multiple ways of importing the polyfill depending on your environment's setup and workflow. I just wanted to check everything. Glad you figured it out yourself, nice work. 😁

And thanks for confirming that it works properly in Safari, I have done only _limited_ tests in it.  

If the issue is resolved we can close it now and if you have any other issue(s), don't hesitate to open a new issue.

**Closed as completed** 2024-09-17 12:48 UTC
Labels: good first issue, question, info-needed
